# Generated by Django 3.0.3 on 2020-02-27 19:24

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, default='', max_length=200),
        ),
    ]
