# Generated by Django 3.0.3 on 2020-02-27 19:29

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200227_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=django_google_maps.fields.AddressField(blank=True, default='', max_length=200),
        ),
    ]
