# Generated by Django 3.0.3 on 2020-02-27 19:38

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, default='', max_length=200),
        ),
    ]
