# Generated by Django 3.0.3 on 2020-02-27 19:41

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200227_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=django_google_maps.fields.AddressField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
