# Generated by Django 3.0.3 on 2020-02-27 20:21

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200227_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='property_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, default='', max_length=200),
        ),
    ]
