# Generated by Django 3.0.5 on 2020-04-24 14:44

import datetime
from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_address', models.CharField(blank=True, default='', max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_range', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('bedrooms', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('one_bedroom_price', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('two_bedroom_price', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('three_bedroom_price', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('four_bedroom_price', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('five_bedroom_price', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('lease_length', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Flexible', 'Flexible'), ('Long Lets', 'Long Lets'), ('Short Lets', 'Short Lets')], default='', max_length=29, null=True)),
                ('security', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('24/7 Onsite Security', '24/7 Onsite Security')], default='', max_length=20, null=True)),
                ('parking', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ground Floor Premise Parking', 'Ground Floor Premise Parking'), ('Underground Parking', 'Underground Parking')], default='', max_length=48, null=True)),
                ('service', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Paint', 'Paint'), ('HVAC', 'HVAC')], default='', max_length=10, null=True)),
                ('features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wifi', 'Wifi'), ('Coffee Shop', 'Coffee Shop'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar')], default='', max_length=31, null=True)),
                ('fitness_recreation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pool', 'Pool'), ('Gym', 'Gym'), ('Tennis Courts', 'Tennis Courts'), ('Game Room', 'Game Room')], default='', max_length=32, null=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='developers.Developer')),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
