# Generated by Django 3.0.5 on 2020-06-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200513_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhome', 'Townhome'), ('Apartment', 'Apartment')], default='', max_length=9, null=True),
        ),
    ]
