# Generated by Django 3.0.4 on 2020-03-09 22:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200308_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wifi', 'Wifi'), ('Coffee Shop', 'Coffee Shop'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar')], default='', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fitness_recreation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pool', 'Pool'), ('Gym', 'Gym'), ('Tennis Courts', 'Tennis Courts'), ('Game Room', 'Game Room')], default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_length',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Flexible', 'Flexible'), ('Long Lets', 'Long Lets'), ('Short Lets', 'Short Lets')], default='', max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ground Floor Premise Parking', 'Ground Floor Premise Parking'), ('Underground Parking', 'Underground Parking')], default='', max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='security',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('24/7 Onsite Security', '24/7 Onsite Security')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='service',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Paint', 'Paint'), ('HVAC', 'HVAC')], default='', max_length=10, null=True),
        ),
    ]
