# Generated by Django 3.0.5 on 2020-06-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
    ]
