# Generated by Django 3.0.5 on 2020-06-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200612_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lng',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
