# Generated by Django 3.0.5 on 2020-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200615_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lng',
        ),
        migrations.AddField(
            model_name='listing',
            name='geo_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
