# Generated by Django 3.0.5 on 2020-06-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200615_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='geo_location',
        ),
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
