# Generated by Django 3.0.5 on 2020-09-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200615_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bathrooms',
            new_name='bathrooms_max',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='five_bedroom_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='four_bedroom_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='one_bedroom_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='three_bedroom_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='two_bedroom_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms_min',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
